import "../styles/global.css";
import { Inter, Lexend } from "next/font/google";
import { IoIosArrowUp } from "react-icons/io";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <>
        <body className={inter.className}>
          <header className="w-full h-16 p-9 border-2 items-center border-b-gray-300 flex justify-between">
            <p className="heading-1-700  bg-gradient-to-r from-primary to-secondary text-transparent bg-clip-text text p-3  ">
              Motors <span className="text-lg font-bold">shop</span>
            </p>
            <div className="flex items-center p-3">
              <button className="btn-header text-lg text-black text-gray-600 hover:font-semibold">
                Fazer login
              </button>
              <button className="btn-header text-lg text-black text-gray-600 hover:font-semibold">
                Cadastrar
              </button>
            </div>
          </header>
          {children}
          <footer className="w-full flex justify-around p-9 h-32 bg-black">
            <div className="flex h-full w-1/4 items-center justify-between gap-2">
              <p className="heading-2-600 text-white ">
                Motors <span className="text-lg">shop</span>
              </p>
            </div>

            <div className="w-96 flex h-full w-1/4 items-center justify-center gap-2">
              <p className="text-white text-sm">
                © 2022 - Todos os direitos reservados.
              </p>
            </div>

            <div className="flex h-full w-1/4 items-center justify-end gap-2">
              <button className="w-12 flex justify-center rounded-md items-center  text-white font-bold bg-gray-900 h-12">
                <IoIosArrowUp className=" text-xl" />
              </button>
            </div>
          </footer>
        </body>
      </>
    </html>
  );
}
